# Generated by Django 3.0.5 on 2020-04-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_store_timestamps_without_timezone_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
