# Generated by Django 3.0.5 on 2020-04-25 11:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_add_user_settings_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='background_color',
            field=colorfield.fields.ColorField(default='#8345BE', max_length=18),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='highlight_color',
            field=colorfield.fields.ColorField(default='#FFCD19', max_length=18),
        ),
    ]
