# Generated by Django 3.0.5 on 2020-04-27 16:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_add_usersettings_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
