# Generated by Django 3.0.5 on 2020-04-27 16:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_usersettings_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='checkmark_color',
            field=colorfield.fields.ColorField(default='#48c774', max_length=18),
        ),
    ]
